language: node_js

# services:
#   - docker

node_js:
  - 12

install:
  # - npm install -g surge
  - npm install

script:
  - npm run build
  - npm run docs:compodoc

after_success:
  - PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yashkumarverma/authentico-backend:${PACKAGE_VERSION} -t yashkumarverma/authentico-backend:latest .
  - docker push yashkumarverma/authentico-backend:${PACKAGE_VERSION}
  - docker push yashkumarverma/authentico-backend:latest
  - surge --project ./documentation --domain authentico-backend.compodoc.surge.sh